### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by maratkhambelov** [maratkhambelov/HomeWork-Lection3-#1]
@coursar, Добрый день, Ильназ, проверьте, пожалуйста ДЗ. Travis и codecov настроил.
Некоторые комментарии:
ДЗ Зодиак - программа работает корректно, но codecov пишет, что остаются непокрытыми несколько строк. В моем случае я создал условие if для того, чтобы проверить корректность веденных пользователем данных. За что codecov и ругает. Как можно улучшить код? Я думал о том, чтобы проверку вывести в отдельную функцию, которая будет вызываться в основной. Подскажите, как правильно сделать.

**Comment by coursar** [comment]
Разнесите проекты по разным репозиториям
